apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ayfn-api
  name: ayfn-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ayfn-api
    spec:
      containers:
        - args:
            - python3

            - lambda_function.py
          env:
            - name: DB_PORT_27017_TCP_ADDR
              value: db
          image: gojira00/ayfn_api
          name: ayfn-api
          ports:
            - containerPort: 5000

          resources: {}

      restartPolicy: Always

status: {}
