apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: plotter
  name: plotter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: plotter
    spec:
      containers:
      - image: ojira00/ayfn_plotter
        name: plotter
        resources: {}
        volumeMounts:
        - mountPath: /plots/
          name: plotterplots
      restartPolicy: Always
      volumes:
      - name: plotterplots
        persistentVolumeClaim:
          claimName: plotterplots
status: {}
