"""helper for launching gunicorn"""

from . import app

GUNICORN_PY = \
'''"""AUTOGENERATED BY web.launch_gunicorn:make_conf
from https://sbest.github.io/post/protips-using-gunicorn-inside-a-docker-image/

"""
from os import environ

for key, value in environ.items():
    if key.startswith('GUNICORN_'):
        gunicorn_key = key.split('_', 1)[1].lower()
        locals()[gunicorn_key] = value
'''

def make_conf():
    """gunicorn hack + entry_point
    https://sbest.github.io/post/protips-using-gunicorn-inside-a-docker-image/
    """
    with open('gunicorn.conf', 'w') as fh:
        fh.write(GUNICORN_PY)

G_APP = app.APP
